### ISSUE TITLE
FFFTP Packages

### ISSUE THREAD

**Issue by gep13** [KageShiron/chocolatey-packages#10]
The last few package versions for FFFTP have had to be rejected due to missing checksums in the installations scripts.  Are you in a position to address this?

**Comment by gep13** [comment]
@KageShiron I wanted to follow up with this, as it looks like new package versions are still being pushed, but without the checksums in the packages.  Are you able to help address this problem?  Thanks

**Comment by KageShiron** [comment]
Sorry, I have missed this issue. 
I'll fix this package soon.

**Comment by gep13** [comment]
@KageShiron thank you very much!

**Comment by gep13** [comment]
This package has been updated.
